"""Initial paper-only schema"""
from alembic import op
import sqlalchemy as sa

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('prop_firm', sa.String(length=64), nullable=True),
    sa.Column('challenge_type', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('risk_policy', sa.JSON(), nullable=False),
    sa.Column('prop_rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mode = 'paper'", name='account_paper_only'),
    sa.CheckConstraint('initial_balance > 0', name='positive_initial_balance'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('economic_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider_key', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('impact', sa.String(length=16), nullable=False),
    sa.Column('occurs_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_key')
    )
    op.create_index(op.f('ix_economic_events_occurs_at'), 'economic_events', ['occurs_at'], unique=False)
    op.create_table('kill_switch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='global_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('extracted_rules', sa.JSON(), nullable=True),
    sa.Column('contradictions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('strategy_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('specification', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('research','backtest','validation','walk_forward','paper','approved')", name='strategy_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version')
    )
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_day', sa.Date(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_index(op.f('ix_account_snapshots_observed_at'), 'account_snapshots', ['observed_at'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=False),
    sa.Column('split', sa.String(length=16), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("split IN ('train','validation','test','walk_forward')", name='dataset_split'),
    sa.CheckConstraint('end_at > start_at', name='valid_test_window'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('improvement_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=True),
    sa.Column('request_key', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('market_context', sa.JSON(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['account_snapshots.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'request_key')
    )
    op.create_index(op.f('ix_signals_account_id'), 'signals', ['account_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('trade_context', sa.JSON(), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('result_r', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('rule_compliant', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('error_type', sa.String(length=32), nullable=True),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_account_id'), 'journal_entries', ['account_id'], unique=False)
    op.create_table('risk_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('policy_snapshot', sa.JSON(), nullable=False),
    sa.Column('rules_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    # ### end Alembic commands ###
    op.execute(sa.text("INSERT INTO kill_switch (id, active, reason, changed_at) VALUES (1, true, 'Initial safety lock', CURRENT_TIMESTAMP)"))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_decisions')
    op.drop_index(op.f('ix_journal_entries_account_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_signals_account_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('improvement_proposals')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_account_snapshots_observed_at'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_table('strategy_versions')
    op.drop_table('knowledge_sources')
    op.drop_table('kill_switch')
    op.drop_index(op.f('ix_economic_events_occurs_at'), table_name='economic_events')
    op.drop_table('economic_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
